apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: canarywatch
  labels:
    app: canarywatch
spec:
  selector:
    matchLabels:
      app: canarywatch
  template:
    metadata:
      labels:
        app: canarywatch
    spec:
      serviceAccountName: canarywatch-sa
      containers:
        - name: canarywatch
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid

